// Master list containing hangman words and corresponding hints
const masterList = [
	["TIKTOK", "What is the name of the international video platform owned by ByteDance?"],
	["DOUYIN", "What is the name of the short video platform launched by ByteDance in 2016?"],
	["LARK", "What is the enterprise workspace used by ByteDance and TikTok employees to collaborate and communicate?"],
	["INSPIRE CREATIVITY", "What is the first half of ByteDance’s mission?"],
	["ENRICH LIFE", "What is the second half of ByteDance’s mission?"],
	["BYTEDANCE", "What is the name of TikTok’s parent company?"],
	["TOUTIAO", "What is the name of the Chinese news and information content platform owned by ByteDance?"],
	["XIGUA VIDEO", "What is the name of the Chinese online video-sharing platform owned by ByteDance?"],
	["HELO", "What is the name of the regional news app owned by ByteDance?"],
	["BYTEPLUS", "What is the name of the ByteDance division which sells AI-powered technologies to businesses outside China?"],
	["VIDEO", "What type of short-form and long-form content does TikTok show users?"],
	["LIVESTREAM", "What type of live content does TikTok offer?"],
	["TIKTOK LIVE", "What platform allows TikTok users and creators to interact in real-time?"],
	["TIKTOK SHOP", "What is the name of TikTok’s e-commerce marketplace?"],
	["FYP", "What is the main page used to consume content on TikTok?"],
	["BYTESTYLES", "What are ByteDance’s core values called?"],
	["AIM FOR THE HIGHEST", "Which ByteStyle is about always pushing boundaries and continuing to grow?"],
	["BE GROUNDED AND COURAGEOUS", "Which ByteStyle is about courage?"],
	["BE OPEN AND HUMBLE", "Which ByteStyle is about humility?"],
	["BE CANDID AND CLEAR", "Which ByteStyle is all about being honest and taking ownership?"],
	["ALWAYS DAY ONE", "Which ByteStyle is related to the number 1?"],
	["CHAMPION DIVERSITY & INCLUSION", "Which ByteStyle promotes inclusivity?"],
	["ONE RAFFLES QUAY", "This is the location of one of our offices in Singapore. Its towers have up to 50 floors."],
	["GUOCO TOWER", "This is the location of one of our offices in Singapore. The tower has up to 65 floors."],
	["DELIVEROO", "What is the name of the company that delivers our meals?"],
	["SHOU ZI CHEW", "Who is TikTok’s CEO?"],
	["ZHANG YIMING", "Who founded ByteDance?"],
	["LIANG RUBO", "Who co-founded ByteDance?"],
	["OKR", "What is the goal-setting methodology used by ByteDance and TikTok to align our global teams towards the same vision?"],
	["CONTENT CREATOR", "What do we call producers of content?"],
	["DANCE CHALLENGE", "What do we call viral TikTok dances?"],
	["RENEGADE", "What viral dance was created by Jalaiah Harmon for the song Lottery by Atlanta rapper K-Camp?"],
	["FRIENDS", "What replaced the Discovery tab of the TikTok app?"],
	["CAPCUT", "What video editing app do TikTok users often use?"],
	["DUETS", "Which TikTok feature lets users post videos side-by-side with a video from another creator?"],
	["REACTIONS", "Which TikTok feature lets users record their reactions to other people’s videos?"],
	["STITCH", "Which TikTok feature lets users clip and integrate scenes from another user's video into their own?"],
	["STORIES", "Which TikTok feature allows users to post videos that disappear after 24 hours?"],
	["SINGAPORE", "Where is the APAC Hub of TikTok located?"],
	["TEN", "How old is ByteDance this year?"],
	["SIX", "How old is TikTok this year?"],
	["GYARU", "What is the name of the latest Korean/Japanese song going viral on TikTok?"],
	["RESSO", "What is the name of the music streaming platform owned by ByteDance?"],
	["EDUTOK", "What TikTok challenge encourages users to create educational and motivational content?"],
	["SEA GAMES", "What sports event did TikTok support in May 2022?"]
];

export default masterList;